### ISSUE TITLE
Extending hijridate to address adjustments based on what is announced as opposed to what is computed currently.

### ISSUE THREAD

**Issue by colathurv** [dralshehri/hijridate#19]
I had a question pertaining to adjustments to Umm al-qura based on this [site] (https://webspace.science.uu.nl/~gent0113/islam/ummalqura_adjust.htm) where in the announced date is different from the computed date, for a few years.  Is there a way to provide a deviation file (deviation.cfg) that annotates deviations. For example, it can say that 1 Ramadan 1424 ==  27 Oct 2023. The expectation here is that the hijridate package would take into account this deviation and generate the calendar to be consistent with this deviation. This means the offsets for hijridate would change and generate the calendar differently.  Appreciate your assistance.

**Comment by dralshehri** [comment]
The Umm al-Qura calendar is a lunar computed civil calendar based on specific astronomical criteria. However, It is limited when the actual sighting of the crescent at the beginning of the month differs. Therefore, you'll find announcements for those adjustments for religious reasons only.

Although having such a feature might be helpful, it can be used only retroactively and requires more frequent updates.

It's in my backlog, and when I find time, I'll think about the appropriate implementation.

Thanks for the suggestion.
