### ISSUE TITLE
Timedelta is not supported for Hijri dates

### ISSUE THREAD

**Issue by afrin1618** [dralshehri/hijridate#21]
Hi Developer,

I am doing a project where I import and use Hijri calendar. But I have noticed that timedelta is not supported for Hijri dates. Please resolve the issue for next release.

Thank You for the calendar!!!

**Comment by dralshehri** [comment]
I appreciate your suggestion.

This feature is indeed on the roadmap, but understanding your specific use case would be extremely helpful. 

Could you please share more details about how you plan to use `﻿timedelta` with `HijriDate`?

**Comment by dralshehri** [comment]
For the time being, you can use the following code to calculate the difference between two Hijri dates in days:

```py
from hijridate import Hijri

h1 = Hijri(1441, 1, 1).to_julian()
h2 = Hijri(1440, 1, 1).to_julian()

print(h1 - h2)
# 354
```
